# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activate/Deactivate')),
                ('created', models.DateTimeField(verbose_name='Creation date/time')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starship_class', models.CharField(max_length=255, verbose_name='Starship Class')),
                ('starship_class_slug', models.SlugField(help_text=' It is used for ORM queryset', verbose_name='Starship Class Slug')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('length', models.CharField(max_length=255, verbose_name='Length')),
                ('hyperdrive_rating', models.CharField(max_length=255, verbose_name='Hyperdrive Rating')),
                ('cargo_capacity', models.CharField(max_length=255, verbose_name='Cargo Capacity')),
                ('crew', models.CharField(max_length=255, verbose_name='Crew')),
                ('passengers', models.CharField(max_length=255, verbose_name='Passengers')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='ship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shiptrader.Starship', verbose_name='Ship Type'),
        ),
    ]
